name: Lint Projeect and nodejs
on: [push, workflow_dispatch]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: SetupNodejs
        uses: actions/setup-node
      - name: install dependencies
        run: npm ci
      - name: run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
